---
Neos:
  MarketPlace:
    typeMapping:
      'typo3-flow-plugin': 'neos-plugin'
      'typo3-flow-build': 'neos-build'
      'typo3-flow-boilerplate': 'neos-boilerplate'
      'typo3-flow-site': 'neos-site'
      'typo3-flow-package': 'neos-package'
      'typo3-flow-framework': 'neos-framework'
      'neos-plugin': 'neos-plugin'
      'neos-build': 'neos-build'
      'neos-boilerplate': 'neos-boilerplate'
      'neos-site': 'neos-site'
      'neos-package': 'neos-package'
      'neos-framework': 'neos-framework'

    repository:
      identifier: '9127231f-d1b8-440f-8ef7-b05f760178fb'

    github:
      cacheDirectory: '%FLOW_PATH_DATA%Github/Cache'
      account: 'username'
      password: 'password'

TYPO3:

  TypoScript:
    defaultContext:
      MarketPlaceSearch: 'Neos\MarketPlace\Eel\ElasticSearchQueryBuilder'
      MarketCaching: 'Neos\MarketPlace\Eel\CachingHelper'

  TYPO3CR:

    Search:
      defaultContext:
        MarketIndexing: 'Neos\MarketPlace\Eel\IndexingHelper'

  Neos:
    typoScript:
      autoInclude:
        'Neos.MarketPlace': true

    nodeTypes:
      groups:
        marketplace:
          position: 'after general'
          label: 'Neos.MarketPlace:Main:nodeTypes.groups.marketplace'

    userInterface:
      translation:
        autoInclude:
          'Neos.MarketPlace': ['Main', 'NodeTypes/*']

Ttree:

  OutOfBandRendering:
    presets:
      'marketplace:version':
        path: 'root<TYPO3.TypoScript:Case>/neosMarketPlaceDocument<TYPO3.TypoScript:Matcher>/element<Neos.MarketPlace:Package.Document>/body<TYPO3.TypoScript:Template>/content/main<TYPO3.TypoScript:Array>/package<Neos.MarketPlace:Package>/versions<Neos.MarketPlace:VersionPreview>'
